### ISSUE TITLE
Compile time too long

### ISSUE THREAD

**Issue by Cifer-Y** [cn/GB2260.ex#2]
Why the compile time soooooooooooo long?
Every compilation costs almost 10 minutes or more.
When I first compiled this, I thought if my computer stoped working.
╮(╯▽╰)╭       

P.S: the most recent compilation cost 12 minutes ╮(╯_╰)╭

**Comment by LcpMarvel** [comment]
This weekend i will try to fix this problem. THX. 

https://github.com/cn/GB2260.ex/blob/master/lib%2Fgb2260%2Fdata.ex#L41

**Comment by LcpMarvel** [comment]
PR is welcome.

**Comment by LcpMarvel** [comment]
Fixed
